#!/usr/bin/env python3
import argparse
import signal
import sys
import time
from pathlib import Path
from threading import Event

from qlc_runtime.artnet import ARTNET_PORT, ArtNetSender
from qlc_runtime.engine import (
    COMPLETED,
    STOPPED,
    TIMEOUT,
    make_blackout_frame,
    run_function,
)
from qlc_runtime.model import ChaserFunction, SceneFunction
from qlc_runtime.network import LIMITED_BROADCAST, derive_broadcast_ip
from qlc_runtime.parser import parse_workspace
from qlc_runtime.select import select_target_function


def send_blackout(sender, repeats: int = 3, interval_s: float = 0.03) -> None:
    blackout = make_blackout_frame()
    for _ in range(max(1, repeats)):
        try:
            sender.send(blackout)
        except OSError:
            # Best-effort safety cleanup; don't mask the original failure path.
            break
        time.sleep(max(0.0, interval_s))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run a QLC+ .qxw show directly to ArtNet (headless)"
    )
    parser.add_argument("show_file", help="Path to QLC+ workspace file (.qxw)")

    parser.add_argument("--ip", default=None, help="Override ArtNet target IP from .qxw")
    parser.add_argument(
        "--bind-ip",
        default=None,
        help="Bind UDP socket to a specific local interface IP (optional)",
    )
    parser.add_argument("--universe", type=int, default=None, help="Override universe ID")
    parser.add_argument("--port", type=int, default=ARTNET_PORT, help="ArtNet UDP port")

    parser.add_argument("--button-id", type=int, default=None, help="Select VC button by ID")
    parser.add_argument(
        "--button-caption",
        default=None,
        help="Select VC button by caption (case-insensitive exact match)",
    )
    parser.add_argument("--function-id", type=int, default=None, help="Run function ID directly")

    parser.add_argument("--fps", type=int, default=40, help="Frame rate for fade interpolation")
    parser.add_argument("--max-seconds", type=float, default=None, help="Optional runtime limit")
    parser.add_argument("--dry-run", action="store_true", help="Parse/schedule only; no UDP send")
    parser.add_argument("--verbose", action="store_true", help="Verbose runtime logs")

    return parser


def main(argv=None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    show_path = Path(args.show_file)
    if not show_path.exists():
        print(f"Error: show file not found: {show_path}", file=sys.stderr)
        return 2

    try:
        workspace = parse_workspace(str(show_path))
        function_id, selected_from = select_target_function(
            workspace,
            function_id=args.function_id,
            button_id=args.button_id,
            button_caption=args.button_caption,
        )
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    fn = workspace.functions[function_id]
    if not isinstance(fn, (SceneFunction, ChaserFunction)):
        print(
            f"Error: unsupported target function type {type(fn).__name__} (ID {function_id})",
            file=sys.stderr,
        )
        return 2

    bind_ip = args.bind_ip or workspace.artnet_ip
    target_ip = args.ip
    auto_target = False
    auto_target_source = None

    if target_ip is None:
        # In .qxw generated by this project, UID is the local ArtNet interface IP.
        # Derive directed broadcast from interface/netmask when possible.
        if bind_ip:
            target_ip, auto_target_source = derive_broadcast_ip(bind_ip)
            auto_target = True
        elif args.dry_run:
            target_ip = "0.0.0.0"
        else:
            print(
                "Error: no ArtNet target IP found. Pass --ip (node or broadcast IP).",
                file=sys.stderr,
            )
            return 2

    target_universe = args.universe
    if target_universe is None:
        target_universe = workspace.artnet_universe if workspace.artnet_universe is not None else 0

    print(f"Show: {show_path}")
    print(f"Selected: {selected_from}")
    print(f"Function: ID={function_id} Name={fn.name!r} Type={type(fn).__name__}")
    print(
        f"ArtNet: {target_ip}:{args.port} universe={target_universe} "
        f"mode={'dry-run' if args.dry_run else 'live'} fps={args.fps}"
    )
    print(f"Bind IP: {bind_ip or 'auto'}")
    if auto_target:
        source = auto_target_source or "auto"
        if target_ip == LIMITED_BROADCAST:
            print(
                f"Target auto-selected from bind/workspace IP {bind_ip} -> {target_ip} "
                f"({source})"
            )
            print(
                "Warning: using limited broadcast fallback. "
                "If fixtures do not respond, pass --ip with your directed broadcast.",
                file=sys.stderr,
            )
        else:
            print(
                f"Target auto-selected from bind/workspace IP {bind_ip} -> {target_ip} "
                f"({source})"
            )
    if not args.dry_run and bind_ip and target_ip == bind_ip:
        print(
            "Warning: target IP equals bind/local IP; this usually means sending to self.",
            file=sys.stderr,
        )
    if args.max_seconds is not None:
        print(f"Max runtime: {args.max_seconds:.2f}s")

    stop_event = Event()
    signal_name = {"name": None}

    def _handle_signal(signum, _frame):
        signal_name["name"] = signal.Signals(signum).name
        stop_event.set()

    sender = ArtNetSender(
        ip=target_ip,
        universe=target_universe,
        port=args.port,
        dry_run=args.dry_run,
        bind_ip=bind_ip,
    )

    try:
        try:
            signal.signal(signal.SIGINT, _handle_signal)
            signal.signal(signal.SIGTERM, _handle_signal)
        except ValueError:
            # Not in main thread (tests): signal setup is optional.
            pass

        def on_step(step_index: int, fade_ms: int, hold_ms: int, step_count: int, scene_name: str):
            print(
                f"Step: idx={step_index} scene={scene_name!r} "
                f"fade={fade_ms}ms hold={hold_ms}ms"
            )

        try:
            result = run_function(
                workspace=workspace,
                function_id=function_id,
                universe=target_universe,
                sender=sender,
                fps=args.fps,
                max_seconds=args.max_seconds,
                should_stop=stop_event.is_set,
                on_step=on_step if (args.verbose or isinstance(fn, ChaserFunction)) else None,
            )
        except OSError as exc:
            print(
                f"Error: ArtNet send failed: {exc}. "
                "Try --bind-ip <local-nic-ip> and/or explicit --ip <node-or-broadcast-ip>.",
                file=sys.stderr,
            )
            return 2

        stop_reason = result.reason
        if stop_reason == STOPPED and signal_name["name"]:
            stop_reason = f"signal {signal_name['name']}"
        elif stop_reason == TIMEOUT:
            stop_reason = "timeout"
        elif stop_reason == COMPLETED:
            stop_reason = "completed"

        print(f"Stop reason: {stop_reason}")
        return 0
    finally:
        # Always fail safe on exit.
        send_blackout(sender)
        sender.close()


if __name__ == "__main__":
    raise SystemExit(main())
