#!/usr/bin/env python3
"""Show workflow helper for song-synced generator creation.

This command gives you a repeatable entry point to:
1) pick an unbuilt song from songs-data
2) scaffold required venue files (research brief + generator stub)
3) print a canonical Codex prompt for full show creation
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Iterable, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VENUE = "venue/home-studio"
SONGS_DATA_DIR = ROOT / "songs-data"

sys.path.insert(0, str(ROOT))

from qlc_runtime.research_gate import resolve_brief_paths, load_and_validate_brief  # noqa: E402


def _song_stems() -> List[str]:
    return sorted(path.stem for path in SONGS_DATA_DIR.glob("*.json"))


def _resolve_song(song_query: str) -> str:
    stems = _song_stems()
    if not stems:
        raise ValueError(f"No song data found in {SONGS_DATA_DIR}")

    if song_query in stems:
        return song_query

    exact_casefold = [stem for stem in stems if stem.casefold() == song_query.casefold()]
    if len(exact_casefold) == 1:
        return exact_casefold[0]
    if len(exact_casefold) > 1:
        raise ValueError(f"Ambiguous song query: {song_query}")

    partial = [stem for stem in stems if song_query.casefold() in stem.casefold()]
    if len(partial) == 1:
        return partial[0]
    if not partial:
        raise ValueError(f"No song match for: {song_query}")
    raise ValueError(
        "Song query matched multiple songs. Be more specific:\n"
        + "\n".join(f"- {stem}" for stem in partial[:12])
    )


def _validate_venue(venue_dir: str) -> Path:
    venue = (ROOT / venue_dir).resolve()
    if not venue.exists() or not venue.is_dir():
        raise ValueError(f"Venue directory does not exist: {venue_dir}")
    if not (venue / "generators").exists():
        raise ValueError(f"Missing generators directory in venue: {venue_dir}")
    if not (venue / "shows").exists():
        raise ValueError(f"Missing shows directory in venue: {venue_dir}")
    return venue


def _generator_path(venue_dir: str, song_stem: str) -> Path:
    return ROOT / venue_dir / "generators" / f"{song_stem}.py"


def _show_path(venue_dir: str, song_stem: str) -> Path:
    return ROOT / venue_dir / "shows" / f"{song_stem}.qxw"


def _brief_paths(venue_dir: str, song_stem: str) -> Tuple[Path, Path]:
    return resolve_brief_paths(project_root=ROOT, song_title=song_stem, venue_dir=venue_dir)


def _brief_is_approved(song_stem: str, venue_dir: str) -> Tuple[bool, str]:
    try:
        load_and_validate_brief(song_title=song_stem, project_root=ROOT, venue_dir=venue_dir)
        return True, "approved"
    except Exception as exc:
        return False, str(exc)


def _load_bpm(song_stem: str) -> int:
    path = SONGS_DATA_DIR / f"{song_stem}.json"
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    bpm = payload.get("bpm", 128)
    try:
        return int(round(float(bpm)))
    except Exception:
        return 128


def _generator_template(song_stem: str, bpm: int) -> str:
    return f"""#!/usr/bin/env python3
\"\"\"Scaffold generator for {song_stem}.

Generated by scripts/show_workflow.py.
\"\"\"

import json
import os
import sys
from typing import Dict, Tuple

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
VENUE_DIR = os.path.dirname(SCRIPT_DIR)
PROJECT_ROOT = os.path.dirname(os.path.dirname(VENUE_DIR))
sys.path.insert(0, PROJECT_ROOT)

from showlib import *

SONG_STEM = {song_stem!r}
BPM = {bpm}

BRIEF = require_research_brief(SONG_STEM, project_root=PROJECT_ROOT, venue_dir=VENUE_DIR)
CREATIVE = build_creative_context(BRIEF, song_stem=SONG_STEM)
BRAND_TOKENS = CREATIVE["brand_tokens"]
CREATIVE_DIRECTIVES = CREATIVE["creative_directives"]
POS: Dict[str, Tuple[int, int, int, int, int, int, int]] = load_focus_position_tuples(
    project_root=PROJECT_ROOT,
    venue_dir=VENUE_DIR,
)

DATA_PATH = os.path.join(PROJECT_ROOT, "songs-data", f"{{SONG_STEM}}.json")
with open(DATA_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)
beats = data.get("beats", [])
segments = data.get("segments", [])

# TODO: replace scaffold logic with full phrase-aware build/drop planning.
# For phrase-aware calls, pass:
#   brand_tokens=BRAND_TOKENS
#   creative_directives=CREATIVE_DIRECTIVES
center = POS.get("C", next(iter(POS.values())))
sharpy_pan, sharpy_tilt, bsw_pan, bsw_tilt, profile_pan, profile_tilt, ni3k_pan = center

scenes = [
    scene("Blackout", *blackout_all()),
    scene(
        "Base Wash",
        sharpy(pan=sharpy_pan, tilt=sharpy_tilt, color7=SHARPY_BLUE, dim=180),
        bsw(pan=bsw_pan, tilt=bsw_tilt, color=BSW_BLUE, dim=170),
        profile(pan=profile_pan, tilt=profile_tilt, color=PROF_BLUE, dim=170),
        fourbar_solid(20, 60, 180),
        *miss_both(10, 40, 140),
        ni3k(r=0, g=30, b=120, halo=H_BLU, dim=180),
    ),
]

main = make_chaser("Main", [0, 1], [hold(BPM, 4), smooth(BPM, 4)])
out = os.path.join(VENUE_DIR, "shows", f"{{SONG_STEM}}.qxw")
write_workspace(out, scenes, [main], bpm=BPM)
print(f"Wrote {{out}} (beats={{len(beats)}}, segments={{len(segments)}})")
"""


def _prompt_text(song_stem: str, venue_dir: str) -> str:
    venue = Path(venue_dir).as_posix()
    return (
        f'Build a show for "{song_stem}" using the full workflow.\n'
        f"- Venue: `{venue}`\n"
        "- Use phrase-aware planning as a hard layer from song-data segments.\n"
        "- Enforce research gate: artist branding + song-title inspiration + sources.\n"
        "- Build creative context from the approved brief and feed brand_tokens + creative_directives into phrase-technique selection.\n"
        "- Keep references/creativity.md venue-agnostic; put venue specifics under venue references.\n"
        f"- Update/create brief in `{venue}/shows/notes/` and generator in `{venue}/generators/`.\n"
        f"- Generate `.qxw` in `{venue}/shows/` and run validators.\n"
    )


def cmd_next(venue_dir: str, limit: int) -> int:
    _validate_venue(venue_dir)
    stems = _song_stems()
    if not stems:
        print("No songs-data JSON files found.")
        return 1

    missing: List[str] = []
    for stem in stems:
        if not _show_path(venue_dir, stem).exists():
            missing.append(stem)

    if not missing:
        print("All songs-data entries already have shows for this venue.")
        return 0

    print(f"Next songs without shows ({venue_dir}):")
    for stem in missing[: max(1, limit)]:
        print(f"- {stem}")
    print("\nUse:")
    print(f'python3 scripts/show_workflow.py scaffold --song "{missing[0]}" --venue {venue_dir}')
    return 0


def cmd_status(venue_dir: str, limit: int) -> int:
    _validate_venue(venue_dir)
    stems = _song_stems()
    if not stems:
        print("No songs-data JSON files found.")
        return 1

    rows: List[Tuple[str, str, str, str]] = []
    for stem in stems:
        gen = _generator_path(venue_dir, stem).exists()
        show = _show_path(venue_dir, stem).exists()
        brief_json, _ = _brief_paths(venue_dir, stem)
        brief_exists = brief_json.exists()
        approved, _ = _brief_is_approved(stem, venue_dir) if brief_exists else (False, "missing")
        rows.append(
            (
                stem,
                "yes" if gen else "no",
                "yes" if show else "no",
                "approved" if approved else ("draft" if brief_exists else "missing"),
            )
        )

    print("song | generator | show | brief")
    print("---|---|---|---")
    for row in rows[: max(1, limit)]:
        print(f"{row[0]} | {row[1]} | {row[2]} | {row[3]}")
    print(f"\nTotal songs: {len(rows)}")
    return 0


def cmd_scaffold(song_query: str, venue_dir: str, overwrite_generator: bool, print_prompt: bool) -> int:
    _validate_venue(venue_dir)
    song_stem = _resolve_song(song_query)
    bpm = _load_bpm(song_stem)

    brief_json, brief_md = _brief_paths(venue_dir, song_stem)
    approved, brief_message = _brief_is_approved(song_stem, venue_dir)
    # load_and_validate_brief creates stubs when missing, so paths now exist.

    generator_path = _generator_path(venue_dir, song_stem)
    generator_path.parent.mkdir(parents=True, exist_ok=True)
    if generator_path.exists() and not overwrite_generator:
        generator_action = "kept"
    else:
        generator_path.write_text(_generator_template(song_stem, bpm), encoding="utf-8")
        generator_action = "written"

    show_path = _show_path(venue_dir, song_stem)

    print(f"Song: {song_stem}")
    print(f"Venue: {venue_dir}")
    print(f"Brief JSON: {brief_json.relative_to(ROOT)}")
    print(f"Brief MD:   {brief_md.relative_to(ROOT)}")
    print(f"Generator:  {generator_path.relative_to(ROOT)} ({generator_action})")
    print(f"Output QXW: {show_path.relative_to(ROOT)}")
    print(f"BPM: {bpm}")
    if approved:
        print("Brief status: approved")
    else:
        print(f"Brief status: draft/not ready ({brief_message})")
        print("Next: fill brief JSON, set status=approved, then run the generator.")

    if print_prompt:
        print("\nPrompt for Codex:")
        print(_prompt_text(song_stem, venue_dir))

    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Show workflow helper")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_next = sub.add_parser("next", help="List songs-data entries missing shows")
    p_next.add_argument("--venue", default=DEFAULT_VENUE, help="Venue dir relative to project root")
    p_next.add_argument("--limit", type=int, default=10, help="Number of songs to print")

    p_status = sub.add_parser("status", help="Show generator/show/brief status")
    p_status.add_argument("--venue", default=DEFAULT_VENUE, help="Venue dir relative to project root")
    p_status.add_argument("--limit", type=int, default=30, help="Max rows to print")

    p_scaffold = sub.add_parser("scaffold", help="Create brief stubs + generator scaffold for a song")
    p_scaffold.add_argument("--song", required=True, help="Song title/stem or partial match")
    p_scaffold.add_argument("--venue", default=DEFAULT_VENUE, help="Venue dir relative to project root")
    p_scaffold.add_argument("--overwrite-generator", action="store_true", help="Overwrite existing generator")
    p_scaffold.add_argument("--no-prompt", action="store_true", help="Do not print Codex prompt")

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        if args.cmd == "next":
            return cmd_next(venue_dir=args.venue, limit=max(1, args.limit))
        if args.cmd == "status":
            return cmd_status(venue_dir=args.venue, limit=max(1, args.limit))
        if args.cmd == "scaffold":
            return cmd_scaffold(
                song_query=args.song,
                venue_dir=args.venue,
                overwrite_generator=bool(args.overwrite_generator),
                print_prompt=not bool(args.no_prompt),
            )
        raise ValueError(f"Unsupported command: {args.cmd}")
    except Exception as exc:
        print(f"Error: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
