#!/usr/bin/env python3
"""Show workflow helper for song-synced generator creation.

This command gives you a repeatable entry point to:
1) pick an unbuilt song from songs-data
2) scaffold required venue files (research brief + generator stub)
3) print a canonical Codex prompt for full show creation
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Iterable, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VENUE = "venue/home-studio"
SONGS_DATA_DIR = ROOT / "songs-data"

sys.path.insert(0, str(ROOT))

from qlc_runtime.research_gate import resolve_brief_paths, load_and_validate_brief  # noqa: E402


def _song_stems() -> List[str]:
    return sorted(path.stem for path in SONGS_DATA_DIR.glob("*.json"))


def _resolve_song(song_query: str) -> str:
    stems = _song_stems()
    if not stems:
        raise ValueError(f"No song data found in {SONGS_DATA_DIR}")

    if song_query in stems:
        return song_query

    exact_casefold = [stem for stem in stems if stem.casefold() == song_query.casefold()]
    if len(exact_casefold) == 1:
        return exact_casefold[0]
    if len(exact_casefold) > 1:
        raise ValueError(f"Ambiguous song query: {song_query}")

    partial = [stem for stem in stems if song_query.casefold() in stem.casefold()]
    if len(partial) == 1:
        return partial[0]
    if not partial:
        raise ValueError(f"No song match for: {song_query}")
    raise ValueError(
        "Song query matched multiple songs. Be more specific:\n"
        + "\n".join(f"- {stem}" for stem in partial[:12])
    )


def _validate_venue(venue_dir: str) -> Path:
    venue = (ROOT / venue_dir).resolve()
    if not venue.exists() or not venue.is_dir():
        raise ValueError(f"Venue directory does not exist: {venue_dir}")
    if not (venue / "generators").exists():
        raise ValueError(f"Missing generators directory in venue: {venue_dir}")
    if not (venue / "shows").exists():
        raise ValueError(f"Missing shows directory in venue: {venue_dir}")
    return venue


def _generator_path(venue_dir: str, song_stem: str) -> Path:
    return ROOT / venue_dir / "generators" / f"{song_stem}.py"


def _show_path(venue_dir: str, song_stem: str) -> Path:
    return ROOT / venue_dir / "shows" / f"{song_stem}.qxw"


def _brief_paths(venue_dir: str, song_stem: str) -> Tuple[Path, Path]:
    return resolve_brief_paths(project_root=ROOT, song_title=song_stem, venue_dir=venue_dir)


def _brief_is_approved(song_stem: str, venue_dir: str) -> Tuple[bool, str]:
    try:
        load_and_validate_brief(song_title=song_stem, project_root=ROOT, venue_dir=venue_dir)
        return True, "approved"
    except Exception as exc:
        return False, str(exc)


def _load_bpm(song_stem: str) -> int:
    path = SONGS_DATA_DIR / f"{song_stem}.json"
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    bpm = payload.get("bpm", 128)
    try:
        return int(round(float(bpm)))
    except Exception:
        return 128


def _generator_template(song_stem: str, bpm: int) -> str:
    return f"""#!/usr/bin/env python3
\"\"\"Scaffold generator for {song_stem}.

BPM: {bpm} | Generated by scripts/show_workflow.py
Customize: palette, position sweeps, section builders, then run.
\"\"\"

import bisect
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
VENUE_DIR = os.path.dirname(SCRIPT_DIR)
PROJECT_ROOT = os.path.dirname(os.path.dirname(VENUE_DIR))
sys.path.insert(0, PROJECT_ROOT)
from showlib import *

# =============================================================================
# LOAD ANALYSIS DATA
# =============================================================================

SONG_STEM = {song_stem!r}
BRIEF = require_research_brief(SONG_STEM, project_root=PROJECT_ROOT, venue_dir=VENUE_DIR)
print(f"Research brief OK: {{BRIEF['_meta']['brief_json']}}")
print(f"Creative thesis: {{BRIEF['thesis']}}")

CREATIVE = build_creative_context(BRIEF, song_stem=SONG_STEM)
BRAND_TOKENS = CREATIVE["brand_tokens"]
CREATIVE_DIRECTIVES = CREATIVE["creative_directives"]

DATA_PATH = os.path.join(PROJECT_ROOT, "songs-data", f"{{SONG_STEM}}.json")
with open(DATA_PATH) as f:
    data = json.load(f)

BPM = data["bpm"]  # {bpm}
beats = data["beats"]
segments = data["segments"]
e_sub = data["energy"]["sub_bass"]
e_rms = data["energy"]["rms"]
vocal_e = data["stems"]["vocals"]["energy"]

BAR_MS = bpm_to_ms(BPM, 4)
BEAT_MS = bpm_to_ms(BPM, 1)

# =============================================================================
# HELPERS
# =============================================================================

def beat_at(t):
    idx = bisect.bisect_left(beats, t)
    if idx == 0: return 0
    if idx >= len(beats): return len(beats) - 1
    return idx if abs(beats[idx] - t) < abs(beats[idx-1] - t) else idx - 1

def avg_energy(arr, t_start, t_end):
    i0, i1 = beat_at(t_start), beat_at(t_end)
    if i0 >= i1: return 0.0
    return sum(arr[i0:i1]) / (i1 - i0)

def segment_at(t):
    for i, seg in enumerate(segments):
        if seg["start"] <= t < seg["end"]:
            return i, seg
    return len(segments) - 1, segments[-1]

def vocal_present(t_start, t_end):
    return avg_energy(vocal_e, t_start, t_end) > 0.015

def e2d(e, lo=30, hi=255):
    return int(lo + (hi - lo) * min(1.0, max(0.0, e)))

# =============================================================================
# PHRASE-AWARE TRACKING
# =============================================================================

PHRASE_USAGE_BY_BUCKET = {{}}
PHRASE_RECENT_BY_BUCKET = {{}}
PHRASE_BAR_COUNTS = {{}}
TECHNIQUE_COUNTS = {{}}
LAST_TECHNIQUE_PLAN = None

def timing_from_phrase_technique(technique, bars_here):
    bars_here = max(0.25, float(bars_here))
    timing = technique["timing"]
    par_style = str(timing["par_style"])
    par_beats = int(timing["par_beats"])
    relationship = str(technique["relationship"])

    if par_style == "fade":
        return smooth(BPM, bars_here)
    if par_style == "chase":
        if par_beats <= 1 and relationship == "inclusion":
            return snap(BPM, bars_here, fade_ms=60)
        if par_beats <= 2:
            return hold(BPM, bars_here)
        return smooth(BPM, bars_here)
    return smooth(BPM, bars_here)

def phrase_step_timing(t_start, t_end, bars_here):
    global LAST_TECHNIQUE_PLAN
    mid = (t_start + t_end) / 2.0
    seg_idx, seg = segment_at(mid)
    label = seg["label"]

    rms = avg_energy(e_rms, t_start, t_end)
    sub = avg_energy(e_sub, t_start, t_end)
    high = rms
    progress = min(1.0, max(0.0, mid / max(1.0, beats[-1])))

    phrase = classify_phrase(
        segment_label=label, rms=rms, sub=sub, high=high,
        progress=progress, project_root=PROJECT_ROOT,
    )

    usage = PHRASE_USAGE_BY_BUCKET.setdefault(phrase, {{}})
    recent = PHRASE_RECENT_BY_BUCKET.setdefault(phrase, [])
    global_bar = int(round((t_start * 1000.0) / BAR_MS))

    technique = pick_phrase_technique(
        phrase=phrase, segment_index=seg_idx, global_bar=global_bar,
        usage=usage, recent=recent, cooldown=2,
        previous_plan=LAST_TECHNIQUE_PLAN,
        brand_tokens=BRAND_TOKENS, creative_directives=CREATIVE_DIRECTIVES,
        candidate_count=3, show_key=SONG_STEM, project_root=PROJECT_ROOT,
    )
    LAST_TECHNIQUE_PLAN = technique
    technique_id = technique["id"]
    usage[technique_id] = usage.get(technique_id, 0) + 1
    recent.append(technique_id)
    if len(recent) > 8:
        del recent[:-8]

    PHRASE_BAR_COUNTS[phrase] = PHRASE_BAR_COUNTS.get(phrase, 0) + max(1, int(round(bars_here)))
    TECHNIQUE_COUNTS[technique_id] = TECHNIQUE_COUNTS.get(technique_id, 0) + 1
    return timing_from_phrase_technique(technique, bars_here), technique

# =============================================================================
# COLOR PALETTE — customize these for your show's aesthetic
# =============================================================================

BASE_COLOR   = (20, 40, 120)    # Deep blue
ACCENT_COLOR = (80, 160, 200)   # Cyan accent
HIT_COLOR    = (200, 220, 255)  # Bright white-blue for peaks
DIM_COLOR    = (10, 15, 40)     # Near-black for low energy
NOTHING      = (0, 0, 0)

# Mover color wheel selections (customize per show)
SH_BASE    = SHARPY_BLUE
SH_ACCENT  = SHARPY_TEAL
BSW_BASE_C = BSW_BLUE
BSW_ACC_C  = BSW_TEAL
PF_BASE_C  = PROF_BLUE
PF_ACC_C   = PROF_TEAL

PALETTE = build_phrase_palette(
    base_rgb=BASE_COLOR, accent_rgb=ACCENT_COLOR, hit_rgb=HIT_COLOR,
    sh_base=SH_BASE, sh_accent=SH_ACCENT, sh_hit=SH_ACCENT,
    bsw_base=BSW_BASE_C, bsw_accent=BSW_ACC_C, bsw_hit=BSW_ACC_C,
    pf_base=PF_BASE_C, pf_accent=PF_ACC_C, pf_hit=PF_ACC_C,
)

# =============================================================================
# POSITIONS
# =============================================================================

POS = load_focus_position_tuples(project_root=PROJECT_ROOT, venue_dir=VENUE_DIR)

# =============================================================================
# SECTIONS — auto-derived from analysis segments
# =============================================================================

SECTIONS = []
for i, seg in enumerate(segments):
    bars = max(1, round((seg["end"] - seg["start"]) * BPM / 240))
    SECTIONS.append({{
        "name": seg["label"], "start": seg["start"],
        "end": seg["end"], "bars": bars, "idx": i,
    }})

# =============================================================================
# SCENE FACTORY
# =============================================================================

scenes = []
folder = SONG_STEM.split(" - ")[-1].split("(")[0].strip() or "Show"
scenes.append(scene("Blackout", *blackout_all(), path=folder))

steps = []
cache = {{}}

def cached(key, fn):
    if key not in cache:
        cache[key] = len(scenes)
        scenes.append(fn())
    return cache[key]


# =============================================================================
# SECTION BUILDERS — dispatched by energy level
# =============================================================================

def build_low(sec):
    \"\"\"Low energy: intro/breakdown/outro — phrase-aware scene factory.\"\"\"
    t, t_end = sec["start"], sec["end"]
    bar = BAR_MS / 1000
    n = 0
    step_bars = 4

    while t < t_end - 0.3:
        next_t = min(t + bar * step_bars, t_end)
        energy = avg_energy(e_rms, t, next_t)
        bars_here = max(0.25, (next_t - t) / bar)
        bars_remaining = max(0, (t_end - next_t) / bar)
        progress = t / max(1.0, beats[-1])

        timing, technique = phrase_step_timing(t, next_t, bars_here)
        phrase = technique.get("phrase", "intro")

        style = resolve_phrase_style(phrase, energy, technique=technique,
                                     song_progress=progress,
                                     bars_left=bars_remaining)
        pos_key = pick_sweep_position(style["pos_style"], n, POS)

        sid = cached(f"low_{{sec['idx']}}_{{n}}", lambda: render_phrase_scene(
            f"{{sec['name']}} {{n}}", style, pos_key, POS, PALETTE,
            beat_idx=n, path=folder))

        br = technique.get("beat_reactivity") or {{}}
        step_bars = reactivity_to_bars(br.get("mover_min", "4bar"))
        steps.append((sid, timing))
        t = next_t
        n += 1


def build_mid(sec):
    \"\"\"Mid energy: verse/build — phrase-aware scene factory.\"\"\"
    t, t_end = sec["start"], sec["end"]
    bar = BAR_MS / 1000
    n = 0
    step_bars = 2

    while t < t_end - 0.3:
        next_t = min(t + bar * step_bars, t_end)
        energy = avg_energy(e_rms, t, next_t)
        bars_here = max(0.25, (next_t - t) / bar)
        bars_remaining = max(0, (t_end - next_t) / bar)
        progress = t / max(1.0, beats[-1])

        timing, technique = phrase_step_timing(t, next_t, bars_here)
        phrase = technique.get("phrase", "verse_groove")

        style = resolve_phrase_style(phrase, energy, technique=technique,
                                     song_progress=progress,
                                     bars_left=bars_remaining)
        pos_key = pick_sweep_position(style["pos_style"], n, POS)

        sid = cached(f"mid_{{sec['idx']}}_{{n}}", lambda: render_phrase_scene(
            f"{{sec['name']}} {{n}}", style, pos_key, POS, PALETTE,
            beat_idx=n, path=folder))

        br = technique.get("beat_reactivity") or {{}}
        step_bars = reactivity_to_bars(br.get("mover_min", "2bar"))
        steps.append((sid, timing))
        t = next_t
        n += 1


def build_high(sec):
    \"\"\"High energy: chorus/drop — phrase-aware scene factory.\"\"\"
    t, t_end = sec["start"], sec["end"]
    bar = BAR_MS / 1000
    n = 0
    step_bars = 2

    while t < t_end - 0.3:
        next_t = min(t + bar * step_bars, t_end)
        energy = avg_energy(e_rms, t, next_t)
        bars_here = max(0.25, (next_t - t) / bar)
        bars_remaining = max(0, (t_end - next_t) / bar)
        progress = t / max(1.0, beats[-1])

        timing, technique = phrase_step_timing(t, next_t, bars_here)
        phrase = technique.get("phrase", "drop")

        style = resolve_phrase_style(phrase, energy, technique=technique,
                                     song_progress=progress,
                                     bars_left=bars_remaining)
        pos_key = pick_sweep_position(style["pos_style"], n, POS)

        sid = cached(f"high_{{sec['idx']}}_{{n}}", lambda: render_phrase_scene(
            f"{{sec['name']}} {{n}}", style, pos_key, POS, PALETTE,
            beat_idx=n, path=folder))

        br = technique.get("beat_reactivity") or {{}}
        step_bars = reactivity_to_bars(br.get("mover_min", "bar"))
        steps.append((sid, timing))
        t = next_t
        n += 1

# =============================================================================
# BUILD SHOW — dispatch sections + insert transitions
# =============================================================================

print(f"Generating show: {{SONG_STEM}}")
print(f"  BPM: {{BPM}}, Beats: {{len(beats)}}, Duration: {{beats[-1]:.1f}}s")
print()

prev_phrase = None
prev_energy = 0.0
recent_transitions = []
last_scene_dict = None

for i, sec in enumerate(SECTIONS):
    energy = avg_energy(e_rms, sec["start"], sec["end"])

    # --- Transition at segment boundary ---
    trans_offset_s = 0.0
    if i > 0:
        cur_phrase = classify_phrase(
            segment_label=sec["name"],
            rms=energy, sub=avg_energy(e_sub, sec["start"], sec["end"]),
            high=energy,
            progress=sec["start"] / max(1.0, beats[-1]),
            project_root=PROJECT_ROOT,
        )
        trans = plan_segment_transition(
            prev_phrase=prev_phrase, next_phrase=cur_phrase,
            prev_energy=prev_energy, next_energy=energy,
            segment_index=i, total_segments=len(SECTIONS),
            recent_transitions=recent_transitions,
            show_key=SONG_STEM,
            end_of_show=(i == len(SECTIONS) - 1),
            prev_segment_beats=SECTIONS[i-1]["bars"] * 4,
            next_segment_beats=sec["bars"] * 4,
            project_root=PROJECT_ROOT,
        )
        t_scenes, t_timing = build_transition_scenes(
            trans, BPM, pos_tuples=POS, palette=ACCENT_COLOR,
            last_scene=last_scene_dict,
        )
        for ts, tt in zip(t_scenes, t_timing):
            idx = len(scenes)
            scenes.append(ts)
            steps.append((idx, tt))
            trans_offset_s += (tt[0] + tt[1]) / 1000.0
        if trans:
            recent_transitions.append(trans["type"])
            if len(recent_transitions) > 6:
                del recent_transitions[:-6]

    # Offset section start so transitions borrow time, not add it
    build_sec = sec
    if trans_offset_s > 0:
        build_sec = {{**sec, "start": sec["start"] + trans_offset_s}}

    # Recompute energy from the actual build window for dispatch
    build_energy = avg_energy(e_rms, build_sec["start"], build_sec["end"])

    # --- Dispatch builder by energy ---
    label = f"  Building {{sec['name']:12s}} ({{sec['bars']:3d}} bars, e={{build_energy:.2f}})"
    if build_energy > 0.6:
        print(f"{{label}} -> HIGH")
        build_high(build_sec)
    elif build_energy > 0.3:
        print(f"{{label}} -> MID")
        build_mid(build_sec)
    else:
        print(f"{{label}} -> LOW")
        build_low(build_sec)

    # Track last scene for freeze-style transitions
    if steps:
        last_scene_dict = scenes[steps[-1][0]]

    prev_phrase = classify_phrase(
        segment_label=sec["name"],
        rms=energy, sub=avg_energy(e_sub, sec["start"], sec["end"]),
        high=energy,
        progress=sec["end"] / max(1.0, beats[-1]),
        project_root=PROJECT_ROOT,
    )
    prev_energy = energy

# Final blackout (short snap, not a full bar — avoids drift)
steps.append((0, snap(BPM, 0.5, fade_ms=100)))

# =============================================================================
# STATS + OUTPUT
# =============================================================================

print(f"\\nTotal scenes: {{len(scenes)}}")
print(f"Total chaser steps: {{len(steps)}}")
print(f"Phrase bars: {{PHRASE_BAR_COUNTS}}")
top_techniques = sorted(TECHNIQUE_COUNTS.items(), key=lambda kv: kv[1], reverse=True)[:8]
print(f"Top technique usage: {{top_techniques}}")

total_ms = sum(fi + ho for _, (fi, ho) in steps)
print(f"Total duration: {{total_ms/1000:.1f}}s (target: ~{{beats[-1]:.0f}}s)")

main_chaser = make_chaser("Main", [s for s, _ in steps], [t for _, t in steps],
                           run_order="SingleShot", path=folder)

vc_buttons = [
    {{"caption": f"\\u25b6 {{folder.upper()}}",  "vc_id": 0, "func_id": len(scenes),
     "x": 10, "y": 10,  "w": 470, "h": 100, "color": "#0A0F78", "action": "Toggle"}},
    {{"caption": "BLACKOUT", "vc_id": 1, "func_id": 0,
     "x": 10, "y": 120, "w": 470, "h": 80,  "color": "#FF0000", "action": "Toggle"}},
]

output_path = os.path.join(VENUE_DIR, "shows", f"{{SONG_STEM}}.qxw")
write_workspace(output_path, scenes, [main_chaser], bpm=BPM, vc_buttons=vc_buttons)
"""


def _prompt_text(song_stem: str, venue_dir: str) -> str:
    venue = Path(venue_dir).as_posix()
    return (
        f'Build a show for "{song_stem}" using the full workflow.\n'
        f"- Venue: `{venue}`\n"
        "- Use phrase-aware planning as a hard layer from song-data segments.\n"
        "- Enforce research gate: artist branding + song-title inspiration + sources.\n"
        "- Build creative context from the approved brief and feed brand_tokens + creative_directives into phrase-technique selection.\n"
        "- Keep references/creativity.md venue-agnostic; put venue specifics under venue references.\n"
        f"- Update/create brief in `{venue}/shows/notes/` and generator in `{venue}/generators/`.\n"
        f"- Generate `.qxw` in `{venue}/shows/` and run validators.\n"
    )


def cmd_next(venue_dir: str, limit: int) -> int:
    _validate_venue(venue_dir)
    stems = _song_stems()
    if not stems:
        print("No songs-data JSON files found.")
        return 1

    missing: List[str] = []
    for stem in stems:
        if not _show_path(venue_dir, stem).exists():
            missing.append(stem)

    if not missing:
        print("All songs-data entries already have shows for this venue.")
        return 0

    print(f"Next songs without shows ({venue_dir}):")
    for stem in missing[: max(1, limit)]:
        print(f"- {stem}")
    print("\nUse:")
    print(f'python3 scripts/show_workflow.py scaffold --song "{missing[0]}" --venue {venue_dir}')
    return 0


def cmd_status(venue_dir: str, limit: int) -> int:
    _validate_venue(venue_dir)
    stems = _song_stems()
    if not stems:
        print("No songs-data JSON files found.")
        return 1

    rows: List[Tuple[str, str, str, str]] = []
    for stem in stems:
        gen = _generator_path(venue_dir, stem).exists()
        show = _show_path(venue_dir, stem).exists()
        brief_json, _ = _brief_paths(venue_dir, stem)
        brief_exists = brief_json.exists()
        approved, _ = _brief_is_approved(stem, venue_dir) if brief_exists else (False, "missing")
        rows.append(
            (
                stem,
                "yes" if gen else "no",
                "yes" if show else "no",
                "approved" if approved else ("draft" if brief_exists else "missing"),
            )
        )

    print("song | generator | show | brief")
    print("---|---|---|---")
    for row in rows[: max(1, limit)]:
        print(f"{row[0]} | {row[1]} | {row[2]} | {row[3]}")
    print(f"\nTotal songs: {len(rows)}")
    return 0


def cmd_scaffold(song_query: str, venue_dir: str, overwrite_generator: bool, print_prompt: bool) -> int:
    _validate_venue(venue_dir)
    song_stem = _resolve_song(song_query)
    bpm = _load_bpm(song_stem)

    brief_json, brief_md = _brief_paths(venue_dir, song_stem)
    approved, brief_message = _brief_is_approved(song_stem, venue_dir)
    # load_and_validate_brief creates stubs when missing, so paths now exist.

    generator_path = _generator_path(venue_dir, song_stem)
    generator_path.parent.mkdir(parents=True, exist_ok=True)
    if generator_path.exists() and not overwrite_generator:
        generator_action = "kept"
    else:
        generator_path.write_text(_generator_template(song_stem, bpm), encoding="utf-8")
        generator_action = "written"

    show_path = _show_path(venue_dir, song_stem)

    print(f"Song: {song_stem}")
    print(f"Venue: {venue_dir}")
    print(f"Brief JSON: {brief_json.relative_to(ROOT)}")
    print(f"Brief MD:   {brief_md.relative_to(ROOT)}")
    print(f"Generator:  {generator_path.relative_to(ROOT)} ({generator_action})")
    print(f"Output QXW: {show_path.relative_to(ROOT)}")
    print(f"BPM: {bpm}")
    if approved:
        print("Brief status: approved")
    else:
        print(f"Brief status: draft/not ready ({brief_message})")
        print("Next: fill brief JSON, set status=approved, then run the generator.")

    if print_prompt:
        print("\nPrompt for Codex:")
        print(_prompt_text(song_stem, venue_dir))

    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Show workflow helper")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_next = sub.add_parser("next", help="List songs-data entries missing shows")
    p_next.add_argument("--venue", default=DEFAULT_VENUE, help="Venue dir relative to project root")
    p_next.add_argument("--limit", type=int, default=10, help="Number of songs to print")

    p_status = sub.add_parser("status", help="Show generator/show/brief status")
    p_status.add_argument("--venue", default=DEFAULT_VENUE, help="Venue dir relative to project root")
    p_status.add_argument("--limit", type=int, default=30, help="Max rows to print")

    p_scaffold = sub.add_parser("scaffold", help="Create brief stubs + generator scaffold for a song")
    p_scaffold.add_argument("--song", required=True, help="Song title/stem or partial match")
    p_scaffold.add_argument("--venue", default=DEFAULT_VENUE, help="Venue dir relative to project root")
    p_scaffold.add_argument("--overwrite-generator", action="store_true", help="Overwrite existing generator")
    p_scaffold.add_argument("--no-prompt", action="store_true", help="Do not print Codex prompt")

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        if args.cmd == "next":
            return cmd_next(venue_dir=args.venue, limit=max(1, args.limit))
        if args.cmd == "status":
            return cmd_status(venue_dir=args.venue, limit=max(1, args.limit))
        if args.cmd == "scaffold":
            return cmd_scaffold(
                song_query=args.song,
                venue_dir=args.venue,
                overwrite_generator=bool(args.overwrite_generator),
                print_prompt=not bool(args.no_prompt),
            )
        raise ValueError(f"Unsupported command: {args.cmd}")
    except Exception as exc:
        print(f"Error: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
